### ISSUE TITLE
Force using .wx broken

### ISSUE THREAD

**Issue by thrust26** [dasm-assembler/dasm#90] opened 2020-09-18 13:11 UTC
This code used to work in previous DASM versions (and using `.wx` was required):

```
RESP0 = $10
...
sta.wx  RESP0,x 
```

With latest DASM it results into: "...error: Illegal forced Addressing mode on 'sta'."

Same when using y-register.

**Comment by msaarna** [comment] 2020-09-18 14:44
No doubt fallout from the big merge.

As a work-around until this is fixed, "sta.w RESP0,x" seems to correctly generate the absolute x-indexed version of the opcode.

**Comment by thomas374b** [comment] 2020-09-18 23:13
I guess it was my fault when I moved the opcode adjustment from main.c to ops.c.

Please take this commit 1b31c7af2352790f402899f5934a65d32b31cc2f  as correction

**Comment by thomas374b** [comment] 2020-09-18 23:32
Maybe there are more hidden bugs that can be targeted to the same code region. This particular tricky piece of code is responsible to pick the right addressing mode out of 3 different sources 
* user forced addressing mode
* addressing mode implied by the instruction
* addressing mode implied by the size of the operands
and matches the result against the adressing modes available to the processor.

I would be glad if I had some more testcases ...  volunteers wanted.

**Comment by dionoid** [comment] 2020-09-23 08:23
I merged the fixes from thomas374b/dasm (commits 45b97e7, 2ac0d2d, 9090da1 and 1b31c7a).
The forced .wx mode is now working again. 

As I know "sta.wx" is used in some example subroutines for the Atari 2600 for setting the X position of any TIA object, should we do an hotfix release after we're all happy with this?

@thomas374b Because of your non-matching dasm fork (accidently caused by me), could you please delete your existing fork and create a new one?

**Comment by dionoid** [comment] 2020-11-09 22:16
Fixed in release 2.20.14.1

**Closed by dionoid** 2020-11-09 22:16 UTC
Labels: bug
