### ISSUE TITLE
Commit history broken ?

### ISSUE THREAD

**Issue by thomas374b** [dasm-assembler/dasm#91] opened 2020-09-19 10:43 UTC
Something must have happened to the commit history of dasm. When I try to check for differences Github tells me

```
There isn’t anything to compare.

thomas374b:master and dasm-assembler:master are entirely different commit histories. 
```

but I have forked from this. How can this happen ?

**Comment by dionoid** [comment] 2020-09-19 10:50
Hi Thomas, sorry for the inconvenience, as I caused this problem by trying to update an incorrect email-address in a few old git commits (which worked, but it created new commit-objects along the way).
Please copy you locally changed files, and do a re-fork of dasm, and copy back your changes in your forked clone.
Again, sorry for this (git still has lots of mysteries to me) and keep these pull-request coming :-)

**Comment by dionoid** [comment] 2020-09-23 08:24
@thomas374b Because of your non-matching dasm fork (accidently caused by me), could you please delete your existing fork and create a new one?

**Comment by dionoid** [comment] 2020-10-04 10:04
Closing this

**Closed by dionoid** 2020-10-04 10:04 UTC
