### ISSUE TITLE
MacOS dasm segfault on long line

### ISSUE THREAD

**Issue by andrew-davie** [dasm-assembler/dasm#11] opened 2019-09-14 10:08 UTC
```
   .byte "|8 17#|7 #17*#|6 #3*13 3*#|6 #2*5 $3 $5 2*#|6 #*2 $14 *#|6 #*10 2#2 $2 *#-2#|6 #*9 #2 #4 *2#2 #|4#2 #*6 $2 #3 #3 *#3 #|#2 2#-#*9 #4 2#@#4 #|2#2 3#*3 $5 #12 #|-2#2 2#*7 $#14 #|2 2#2 #*-$6 #3 .#5 .#2 #|3 4#*8 #3 2#3 #-2#2 #|5 2#*5 $2 #-2.9 2.#|6 #2*-$5 #-2.-#2 #2 #-2.#|6 #3*7 #3 7#2 #|5 3#10*#10 #|4 #3 21#|4 #2 2#-#2 #5 #2 #-#2 #|4 4#2 3#7 3#2 2#"
```

The above causes a segfault. I suspect it's any long lines like this, but that's the actual line where I found the issue. Normally easy enough to avoid - but...

a) the code is auto-generated so a pain to have to break into multiple lines
b) in my actual use-case, the string is passed to a macro. However the above .byte as a stand-alone will trigger the segfault. But requiring the one string to pass to the macro is why I can't easily split lines.
b) DASM should not segfault under any circumstances! If the line's too long, then say so!

**Comment by neilsf** [comment] 2019-11-05 06:50
I can confirm this is a bug in Linux as well.

**Comment by msaarna** [comment] 2019-12-11 19:16
The cause of the segfault was an overflow in a buffer used for .byte opcode processing. I've updated 2.20.12. The buffer in question now uses the same sizing constant as the line buffer, and I've added a test case.
Closing the issue.

**Closed by msaarna** 2019-12-11 19:16 UTC
Labels: bug
